@startuml Initial-ZigZag


title Estratégia Inicial - Zig-Zag

[*] --> Config
Config --> ZigZag
ZigZag --> AvoidEdge : BorderDetected
AvoidEdge --> ZigZag

/'
' Descrições
'/

'Escolher um melhor nome para a ação do estado "AvoidEdge"
Config : setTimeout();
ZigZag : movimentsToFollow();
AvoidEdge : edgeCases();

@enduml