@startuml Search-Radar

title Estratégia de Busca - Radar

state switch <<choice>>

[*] --> switch
switch -l-> rotate_left  : [sideLastSeen == left]
switch -r-> rotate_right : [sideLastSeen == right]

/'
' Descrições
'/

@enduml