@startuml Events

title Situações/Leituras e seus eventos correspondentes


state Leituras{
    Parar_o_Robo -[hidden]-> EncerrarEstadoAtual
    EncerrarEstadoAtual -[hidden]-> Comecar_a_luta
    Comecar_a_luta -[hidden]-> BordaDetectada
    BordaDetectada -[hidden]-> OponenteDetectado
}
state Eventos_Gerados{
    Terminate -[hidden]-> Timeout
    Timeout -[hidden]-> Start
    Start -[hidden]-> BorderDetected
    BorderDetected -[hidden]-> OpponentDetected
}

Parar_o_Robo -> Terminate
EncerrarEstadoAtual -> Timeout
Comecar_a_luta -> Start
BordaDetectada -> BorderDetected
OponenteDetectado -> OpponentDetected
/'
' Descrições
'/


@enduml