@startuml Search
/' 
 ' CCW = Counter Clockwise
 ' CW  = Clockwise
 '
 ' Os sensores são observados como se o centro do robô
 ' estivesse no centro de uma rosa dos ventos.
 ' Portanto:
 ' West ( W ) = Sensor Lateral Esquerdo
 ' NorthWest ( NW ) = Sensor Frontal Esquerdo
 ' NorthNorthWest ( NNW ) = Sensor Frontal Esquerdo + Central
 ' North ( N ) = Sensor Central
 ' NorthNorth ( NNE ) = Sensor Frontal Direito + Central
 ' NorthEast ( NE ) = Sensor Frontal Direito
 ' East ( E ) = Sensor Direito
 '/

[*] -d--> Blind
Blind -l--> NorthWest : DLSensor
Blind -d-> North : CSensor
Blind -r--> NorthEast : DRSensor

NorthWest -r-> NorthNorthWest : CSensor
NorthWest --u-> Blind : !DLSensor
NorthWest -u-> West : LSensor
NorthWest --d--> TrueNorth : DRSensor

West -d-> NorthWest : !LSensor

NorthEast -l-> NorthNorthEast : CSensor
NorthEast --u-> Blind : !DRSensor
NorthEast -u-> East : RSensor
NorthEast --d--> TrueNorth : DLSensor

East -d-> NorthEast : !RSensor

NorthNorthWest -d-> TrueNorth : DRSensor
NorthNorthWest -l-> NorthWest : !CSensor
NorthNorthWest -r-> North : !DLSensor

North -l-> NorthNorthWest : DLSensor
North -r-> NorthNorthEast : DRSensor
North -u-> Blind : !CSensor

NorthNorthEast -l-> North : !DRSensor
NorthNorthEast -r-> NorthEast : !CSensor
NorthNorthEast -d-> TrueNorth : DLSensor

TrueNorth -u-> NorthNorthWest : !DRSensor
TrueNorth -u-> NorthNorthEast : !DLSensor

/'
 ' Descrições
 '/

Blind : Swip ( lastSeen )
Blind : Star ( )

NorthWest : CloseArc ( counterClockWise )
NorthWest : lastSeen = left

West : Swip ( counterClockWise )
West : lastSeen = left

NorthEast : CloseArc ( clockWise )
NorthEast : lastSeen = right

East : Swip ( clockWise )
East : lastSeen = right

North : Foward  ()

NorthNorthWest : OpenArc ( counterClockWise )
NorthNorthWest : lastSeen = left

NorthNorthEast : OpenArc ( clockWise )
NorthNorthEast : lastSeen = right

TrueNorth : Forward ( )

@enduml