@startuml RadarSearch

title Busca por Radar

[*] --> Dojo
Dojo -> OnEdge : BorderDetected
OnEdge -> Dojo

state Dojo{
    [*] --> Blind
    Blind -> Chase : OpponentDetected
    Chase -> Blind : OpponentLost
}

/'
' Descrições
'/

Blind : radar()
Chase : chaseAction() (PID)
OnEdge : avoidEdge()

@enduml