@startuml RadarSearch

title Busca por Radar

[*] --> Dojo
Dojo -> OnEdge : Border Detected
OnEdge -> Dojo : Border Lost

state Dojo{
    [*] --> Blind
    Blind -> Chase : Opponent Detected
    Chase -> Blind : Opponent Lost
}

/'
' Descrições
'/

Blind : radar()
Chase : chaseAction() (PID)
OnEdge : avoidEdge()

@enduml