@startuml Initial-Arch

title Estratégia Inicial - Arco

[*] --> Config
Config --> Arch
Arch --> Arch
Arch --> AvoidEdge : BorderDetected
AvoidEdge -d-> Arch


/'
' Descrições
'/

Config : setTimeout()
Arch : Movimentos to follow
AvoidEdge : rotateInward()

@enduml