@startuml Initial-RadarAtrasado

title Estratégia Inicial - Radar Atrasado

[*] --> SetTimeout
SetTimeout --> Seeing
Seeing -l-> Rotate_Left : [left]
Seeing -r-> Rotate_Right : [right]
Rotate_Left --> StayStopped : [opponentInFront]
Rotate_Right --> StayStopped : [opponentInFront]
StayStopped -u-> Seeing : [lostOpponent]

/'
' Descrições
'/

SetTimeout : setTimeout(1000);
Rotate_Left : driveRobot(0, -1 * robotConfiguration.radarSpeed);
Rotate_Right : driveRobot(0, 1 * robotConfiguration.radarSpeed);
StayStopped : stopMotors();
Blind : driveRobot(0, pid(getErrorFromOPSensors()));

@enduml