@startuml Initial-RadarAtrasado

title Estratégia Inicial - Radar Atrasado

[*] --> SetTimeout
SetTimeout --> Seeing
Seeing -l-> Rotate_Left : [lostLeft]
Seeing -r-> Rotate_Right : [lostRight]
Rotate_Left -r-> Seeing : [foundOpponent]
Rotate_Right -l-> Seeing : [foundOpponent]
Seeing --> StayStopped : [opponentInFront]
StayStopped -u-> Seeing : [lostOpponent]

/'
' Descrições
'/

SetTimeout : setTimeout(1000);
Rotate_Left : driveRobot(0, -1 * robotConfiguration.radarSpeed);
Rotate_Right : driveRobot(0, 1 * robotConfiguration.radarSpeed);
StayStopped : stopMotors();
Seeing : driveRobot(0, pid(getErrorFromOPSensors()));

@enduml